<<<<<<< HEAD
spring.application.name=study_apir
server.port=8080
springdoc.swagger-ui.path=/
api.version=v1
=======
spring.application.name=study-apir
>>>>>>> e25d90fc201d70606d54d478440bfa3ecef8b862
